sygmaprotocol/sygma-ui

.github/workflows/deploy_ecs-config-server_STAGE.yaml, .github/workflows/deploy_ecs-transfer-ui_STAGE.yaml, .github/workflows/docker-build-and-push.yml, .github/workflows/release.yml
=> update github actions ubuntu

packages/core/package.json, packages/core/src/contexts/Adaptors/EVMAdaptors/makeDeposit.ts, packages/example/package.json, yarn.lock
=> fix of deposit event listener 

package.json
=> fix license on package.json

packages/example/src/modules/TransferActiveModal/TransferActiveModal.tsx
=> hot fix name of one variable

packages/example/src/pages/TransferPage/TransferPage.tsx
=> Reset form

packages/sygma-ui/package.json, packages/sygma-ui/src/pages/TransferPage/TransferPage.tsx, packages/sygma-ui/src/pages/TransferPage/styles.ts, yarn.lock
=> Add faucetUI link on TransferUI

packages/sygma-ui/src/pages/TransferPage/HomeNetworkConnectView.tsx, packages/sygma-ui/src/pages/TransferPage/TransferPage.tsx
=> fix transfers when more then 2 networks

packages/sygma-ui/src/contexts/Adaptors/EVMAdaptors/EVMDestinationAdaptorProvider.tsx, packages/sygma-ui/src/contexts/Adaptors/EVMAdaptors/handleProposalEvent.ts
=> fix directions in handle destination

.github/workflows/deploy_ecs-config-server_TESTNET.yaml
updating config-server testent
=> deploy testnet config

.github/workflows/deploy_ecs-transfer-ui_TESTNET.yaml
=> chore: update testnet pipeline

.github/workflows/deploy_ecs-config-server_TESTNET.yaml
updated pipeline cluster and service name
updated cluster name 
updated service name
=> chore: updated cluster

.github/workflows/deploy_ecs-config-server_TESTNET.yaml
=> Testupdate

.github/workflows/deploy_ecs-transfer-ui_TESTNET.yaml
modified cluster and service name
=> chore: update cluster-service name

package.json, packages/sygma-ui/package.json, packages/sygma-ui/src/contexts/Bridge/Bridge.tsx, yarn.lock
Update Sygma SDK version
Closes: #69
=> Update Sygma SDK version in Sygma UI

package.json, yarn.lock
=> fix: Update dependency in root package.json

.github/workflows/deploy_ecs-config-server_STAGE.yaml, .github/workflows/deploy_ecs-config-server_TESTNET.yaml
Changed naming convention for visibility
=> chore: changed pipeline name

package.json, packages/sygma-ui/package.json, yarn.lock
=> bump sygma sdk version to 1.1.3

packages/sygma-ui/src/pages/NftTransferPage/NftTransferPage.tsx, packages/sygma-ui/src/pages/TransferPage/TransferPage.tsx
=> recalculate the fee when destination network is changed

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml
Changed url from chainsaf.io to buildthsygma.com
=> chore: changed old url to buildwithsygma.com

.yarnrc.yml, Dockerfile, server.dockerfile
=> Changed to corepack in dockerfile

packages/sygma-ui/src/App.tsx, packages/sygma-ui/src/components/AddressInput/AddressInput.tsx, packages/sygma-ui/src/components/HomeNetworkConnectView/HomeNetworkConnectView.tsx, packages/sygma-ui/src/components/SelectDestinationNetwork/index.tsx, packages/sygma-ui/src/components/TokenInput/TokenInput.tsx, packages/sygma-ui/src/components/TokenSelectInput/TokenSelectInput.tsx, packages/sygma-ui/src/pages/TransferPage/TransferPage.tsx, packages/sygma-ui/src/themes/nftPageTheme.ts
Implements theme and styles changes for the UI. This is basic implementation and doesn't take into consideration changes over component logic present in the new figma mocks
Closes: #116
=> chore: style and theme changes for transfer UI

packages/sygma-ui/src/configLoader/getSharedConfig.ts
It fixes error to fetch shared config
=> fix: fix error on url for shared config

packages/sygma-ui/src/configLoader/getSharedConfig.ts
- remove port to resolve redirection
=> fix: Fix/remove port shared config

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml
=> fix: removing protocol from url

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml, packages/sygma-ui/src/configLoader/getSharedConfig.ts
- restore protocol and adding log
=> fix: Fix/remove protocol from url

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml, packages/sygma-ui/src/configLoader/getSharedConfig.ts
=> fix: url and log

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml, Dockerfile, packages/sygma-ui/src/configLoader/getSharedConfig.ts
update on docker file and task definition
=> fix: docker file and task definition

.github/workflows/deploy_ecs-transfer-ui_STAGE.yaml
Update shared config ipfs url for devnet
=> update shared config ipfs url for devnet
